feat: написал основной проект
M0L0D0Y/java-explore-with-me pull request #1
Opened 2022-10-26 11:56 UTC by M0L0D0Y

2022-10-27 22:45 UTC, db-exp requested changes

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/category/Category.java
> +    @Column(name = "name")
Нужно добавить валидацию Size

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/compilation/Compilation.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
Почему не instanceof?

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private String title;
Нужно добавить валидацию Size и null/не null

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ApiError.java
> +    /*status = Enum: [ 100 CONTINUE,
лучше удалить ненужный код

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ApiError.java
> +package ru.practicum.ewm.ecxeption;
ecxeption - опечатка

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ErrorHandler.java
> +    public ApiError handleConflictDataTimeException(final ConflictDataTimeException e) {
Тут BAD_REQUEST, FORBIDDEN про права

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/Event.java
> +public class Event {
Нужно добавить валидацию на String - Size,  null/ не null

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/Event.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
тот же вопрос - почему не instanceof?

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +    private void sendToStatServer(HttpServletRequest request) {
Лучше в самом верху достать из запроса 3 параметра и не смешивать слои - контроллера и сервисов

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventController.java
> +                rangeEnd, onlyAvailable, sort, from, size, request);
Вот тут уже request не нужно пробрасывать, либо информацию из него напрямую, либо обернуть в объект - UserInfo  или как-то еще

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
Нужно добавить валидацию String на Size, null/ не null

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private String state;//Enum: [ PENDING, PUBLISHED, CANCELED ]
Лучше enum

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventController.java
> +    @GetMapping(value = "/admin/events")
Нужно вынести admin в отдельный контроллер, смешивать админское и публичное - плохая практика

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +public class User {
Нужно добавить валидацию на String - Size, null/не null

2022-10-27 22:45 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/participationRequest/ParticipationRequest.java
> +public class ParticipationRequest {
Нужно добавить валидацию на String - Size, null/не null

2022-10-27 22:45 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/model/EndpointHit.java
> +public class EndpointHit {
Нужно добавить валидацию на String - Size, null/не null

2022-10-27 22:45 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/model/NewEndpointHitDto.java
> +public class NewEndpointHitDto {
Нужно добавить валидацию на String - Size, null/не null

2022-10-27 22:45 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/service/ConverterDataTime.java
> +   // private static final String PATTERN = "yyyy-MM-ddTHH:mm:ss";
нужно удалить старый код

2022-10-27 22:45 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/service/ConverterDataTime.java
> +    private static final String PATTERN = "yyyy-MM-dd HH:mm:ss";
паттерн встречается в других классах, может лучше вынести в отдельный класс с константами?

2022-10-28 07:36 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/category/Category.java
> +    @Column(name = "name")
Добавил

2022-10-28 07:40 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/compilation/dto/NewCompilationDto.java
> +    private String title;
Добавил валидацию Size и NotNull

2022-10-28 07:41 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ApiError.java
> +    /*status = Enum: [ 100 CONTINUE,
удалил коментарии

2022-10-28 07:42 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ApiError.java
> +package ru.practicum.ewm.ecxeption;
исправил

2022-10-28 07:43 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/ecxeption/ErrorHandler.java
> +    public ApiError handleConflictDataTimeException(final ConflictDataTimeException e) {
исправил на BAD_REQUEST

2022-10-28 08:02 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +    private void sendToStatServer(HttpServletRequest request) {
Перенес отправку данных в контроллер

2022-10-28 08:05 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/dto/UpdateEventRequest.java
> +public class UpdateEventRequest {
Добавил валидации

2022-10-28 08:20 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/Event.java
> +public class Event {
Добавил валидации

2022-10-28 08:22 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +public class User {
Добавил валидации

2022-10-28 08:24 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/participationRequest/ParticipationRequest.java
> +public class ParticipationRequest {
Добавил валидации

2022-10-28 08:31 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/model/EndpointHit.java
> +public class EndpointHit {
Добавил валидации

2022-10-28 08:31 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/service/ConverterDataTime.java
> +   // private static final String PATTERN = "yyyy-MM-ddTHH:mm:ss";
удалил

2022-10-28 08:48 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventController.java
> +                rangeEnd, onlyAvailable, sort, from, size, request);
убрал, т.к. передаю инфу напрямую из контроллера

2022-10-28 08:54 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/model/NewEndpointHitDto.java
> +public class NewEndpointHitDto {
Добавил валидации

2022-10-28 08:58 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    private String state;//Enum: [ PENDING, PUBLISHED, CANCELED ]
Исправил на Enum

2022-10-28 10:05 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/EventController.java
> +    @GetMapping(value = "/admin/events")
сделал отдельные контроллеры и сервисы для запросов от админа

2022-10-28 10:18 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/compilation/Compilation.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
не припомню чтобы такое проходили. исправил метод с использованием instanceof

2022-10-28 10:18 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/Event.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
не припомню чтобы такое проходили. исправил метод с использованием instanceof

2022-10-28 10:20 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/service/ConverterDataTime.java
> +    private static final String PATTERN = "yyyy-MM-dd HH:mm:ss";
в каждом модуле он встречается только 1 раз

2022-10-28 19:41 UTC, db-exp requested changes

2022-10-28 19:41 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/exception/ApiError.java
> +@Data
Data вроде как нельзя - давай поменяем на Getter/Setter/ToString если нужно

2022-10-28 19:41 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +    @Column(name = "name")
Нужен Size/null/не null

2022-10-28 19:41 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +    private String email;
Нужен Size/null/не null

2022-10-28 19:41 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/model/EndpointHit.java
> +public class EndpointHit {
На String полях не появились size/null/не null

2022-10-28 19:41 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/model/NewEndpointHitDto.java
> +public class NewEndpointHitDto {
На String полях не появились size/null/не null

2022-10-28 19:41 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/AdminEvenServiceImpl.java
> +public class AdminEvenServiceImpl implements AdminEvenService {
Опечатка - AdminEven

2022-10-28 19:41 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/event/AdminEvenService.java
> +public interface AdminEvenService {
Опечатка - AdminEven

2022-10-28 20:33 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/exception/ApiError.java
> +@Data
заменил на 
@Getter
@Setter
@ToString
@RequiredArgsConstructor

2022-10-28 20:39 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +    private String email;
для всех полей String моделей user добавил NotBlank, для name еще добавил  @Size

2022-10-28 20:41 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/AdminEvenServiceImpl.java
> +public class AdminEvenServiceImpl implements AdminEvenService {
исправил

2022-10-28 20:42 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/user/User.java
> +    @Column(name = "name")
для всех полей String моделей user добавил NotBlank, для name еще добавил Size

2022-10-28 21:10 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/event/AdminEvenService.java
> +public interface AdminEvenService {
исправил

2022-10-28 21:11 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/model/NewEndpointHitDto.java
> +public class NewEndpointHitDto {
этот класс не использую. удалил

2022-10-28 21:12 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/model/EndpointHit.java
> +public class EndpointHit {
добавил Notblank и Size

2022-10-29 08:51 UTC, db-exp approved these changes

2022-10-29 09:07 UTC, merged