Feature
M0L0D0Y/java-explore-with-me pull request #2
Opened 2022-10-31 09:57 UTC by M0L0D0Y

2022-10-31 17:33 UTC, EvgeniPolyakov reviewed
Оставил некоторые замечания. Надеюсь, будут полезными.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +package ru.practicum.ewm.feature;
Возможно, есть резон переименовать пакет, чтобы название более точно отражало его функционал. Например, subscription, friends, feed и т.п.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +@RequestMapping
"/users/{userId}/friends/" - общая начальная часть для всех эндпоинтов, которую можно вынести в @RequestMapping(path = "/users/{userId}/friends/")

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +        return "Пользователь добавлен в друзья";
Скажу откровенно, прежде не сталкивался с использованием стринга в качестве возвращаемого значения функции, так что не обладаю компетенциями в этом вопросе, но на подсознательном уровне мне кажется, что более конвенционально было бы сделать методы void (о том, что добавление или удаление успешно прошли, говорит респонс 200), а информационные сообщения вынести в лог. Тем более, что у класса стоит аннотация @Slf4j, а самих логов нет. Логгирование надо бы добавить ко всем эндпоинтам.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +                                               @RequestParam(defaultValue = "false") @NotNull Boolean common) {
У переменной common (я бы переименовал переменную в нечто более информативное: isCommonFriend или как-то так) может быть только два значения, так что лично я бы использовал примитивный тип boolean. Тем более, что затем в во FriendService она всё равно анбоксится в примитив (строчка 17 в интерфейсе FriendService).

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +                             CommonMethods commonMethods,
Не относится к кодревьюингу функционалу подписки, но CommonMethods по своей сути тоже является сервисом и для единообразия его можно переименовать в какой-нибудь 'service'. Например, условный utilityService или нечто подобное.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +                             ParticipationRequestStorage participationRequestStorage) {
Мне кажатеся, с точки зрения принципов SOLID неверно, чтобы FriendService обращался напрямую в репозиторий реквестов. Я бы сделал participationRequestStorage доступным только со стороны ParticipationRequestService, и за нужной логикой обращался бы в созданные в нём соответствующие методы.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +@Transactional
Так как методы add и delete помечены аннотацией @Transactional, а у методов типа get транзакционная аннотация отсутствует вовсе, полагаю, тут подразумевалось @Transactional(readOnly = true)

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        user.setFriends(listFriends);
Нет необходиомсти сетить коллекцию друзей. Мы работаем с ссылкой на объект, а он, и так, ссылается на эту коллекцию

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        userStorage.save(user);
Сохранение не требуется. выше мы получаем ссылку на объект, полученный из бд, а значит изменения будут автоматически зафиксированы, так как мы работаем в рамках транзакции.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +    public List<Event> getEventsByFriendId(long userId, long friendId, boolean common) {
Я бы переименовал переименную в более информативную: isCommonFriend или нечто подобоное.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        if (!common) {
Чистой воды вкусовщина с моей стороны, но я бы обратил условие if/else, чтобы условие в скобках не шло через отрицание. По факту не имеет принципиального значения.

2022-10-31 17:39 UTC, EvgeniPolyakov commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        for (User u : listFriends) {
Изымание айди можно также реализовать через стрим, но это, опять же сугубо вкусовщина.

2022-10-31 18:03 UTC, EvgeniPolyakov commented on main-service-spec/src/main/resources/schema.sql
> +);
Я бы добавил составной PRIMARY KEY (user_id, friend_id)

2022-10-31 18:14 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +package ru.practicum.ewm.feature;
переименовал пакет

2022-10-31 18:16 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +@RequestMapping
вынес общий путь всех эндпоинтов в @RequestMapping

2022-10-31 18:18 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +        return "Пользователь добавлен в друзья";
убрал @slf4j т.к. логи пишутся в сервисе. Методы возвращающие строку исправил на void

2022-10-31 18:21 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendController.java
> +                                               @RequestParam(defaultValue = "false") @NotNull Boolean common) {
переименовал переменную на isCommonFriend

2022-10-31 18:22 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +                             CommonMethods commonMethods,
этот класс был проверен ревьюером, у него вопросов не возникло, оставлю пока так

2022-10-31 18:25 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +                             ParticipationRequestStorage participationRequestStorage) {
у меня много где так сделано. у ревьюера вопросов не возникало...

2022-10-31 18:29 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +@Transactional
прописал @Transactional(readOnly = true)

2022-10-31 18:33 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        if (!common) {
так простл чуть короче

2022-10-31 18:34 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +    public List<Event> getEventsByFriendId(long userId, long friendId, boolean common) {
переименовал на isCommonFriend

2022-10-31 18:37 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        user.setFriends(listFriends);
исправил

2022-10-31 18:37 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        userStorage.save(user);
исправил

2022-10-31 18:46 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/feature/FriendServiceImpl.java
> +        for (User u : listFriends) {
стримами плохо владею. поэтому написал так

2022-10-31 18:53 UTC, M0L0D0Y commented on main-service-spec/src/main/resources/schema.sql
> +);
добавил составной PRIMARY KEY (user_id, friend_id)

2022-11-03 22:46 UTC, db-exp requested changes

2022-11-03 22:46 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/endpiont/EndpointHitStorage.java
> +package ru.practicum.ewm.endpiont;
опечатка - endpoint

2022-11-03 22:46 UTC, db-exp commented on stat-service/src/main/java/ru/practicum/ewm/endpiont/EndpointController.java
> +package ru.practicum.ewm.endpiont;
я бы разбил файлы по пакетам

2022-11-03 22:46 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/client/BaseClient.java
>  public class BaseClient {
сейчас нет особо смысл делить BaseClient и StatsClient - в Base лежат методы для запроса Stats, кажется, лучше слить в один класс

2022-11-03 22:46 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/client/BaseClient.java
> +            return stats.length > 0 ? stats[0] : null;
а почему только stats[0] - запрос же возвращает список

2022-11-03 22:46 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/subscription/SubscriptionServiceImpl.java
> +        List<Long> idFriends = new LinkedList<>();
Зачем LinkedList?

2022-11-04 09:40 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/endpiont/EndpointController.java
> +package ru.practicum.ewm.endpiont;
разбил по пакетам

2022-11-04 09:41 UTC, M0L0D0Y commented on stat-service/src/main/java/ru/practicum/ewm/endpiont/EndpointHitStorage.java
> +package ru.practicum.ewm.endpiont;
удалил пакет

2022-11-04 09:42 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/client/BaseClient.java
> +            return stats.length > 0 ? stats[0] : null;
в методе запрашивается 1 конкретный url, и в списке получится только 1 объект. он нам и нужен, для того чтобы получить просмотры для конкретного ивента

2022-11-04 09:44 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/subscription/SubscriptionServiceImpl.java
> +        List<Long> idFriends = new LinkedList<>();
изменил на ArrayList

2022-11-04 10:12 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/client/BaseClient.java
>  public class BaseClient {
убрал BaseClient

2022-11-04 11:19 UTC, db-exp requested changes

2022-11-04 11:19 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/MainServiceSpec.java
> +    @Bean
Лучше не делать это в Main, а вынести в отдельный класс с Configuration аннотацией

2022-11-04 11:19 UTC, db-exp commented on main-service-spec/src/main/java/ru/practicum/ewm/subscription/SubscriptionServiceImpl.java
> +@Transactional(readOnly = true)
не особо нужно, на каждом методе внутри уже есть и местами не только на read

2022-11-04 14:11 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/subscription/SubscriptionServiceImpl.java
> +@Transactional(readOnly = true)
убрал @Transactional

2022-11-04 14:13 UTC, M0L0D0Y commented on main-service-spec/src/main/java/ru/practicum/ewm/MainServiceSpec.java
> +    @Bean
Вынес в отдельный класс с @Configuration

2022-11-04 17:32 UTC, db-exp approved these changes

2022-11-05 15:14 UTC, merged